In [2]:
import numpy as np

A = np.arange(3)
B = np.arange(6).reshape((2, 3))
print(A)
print(B)
print(np.exp(A))
print(np.sqrt(A))
print(np.sum(B, axis=0))
print(np.cumsum(B, axis=0))
print(np.var(B, axis=0))

[0 1 2]
[[0 1 2]
 [3 4 5]]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[3 5 7]
[[0 1 2]
 [3 5 7]]
[2.25 2.25 2.25]


In [3]:
a = np.floor(np.random.randn(3, 4))
print(a)
print('------')
print(a.ravel())
print('-------')
a.shape = (2, 6)        # a.reshape(2, -1)
print(a)
print('------')
print(a.T)

In [4]:
# 拼接操作
a = np.floor(np.random.randn(2, 2))
b = np.floor(np.random.randn(2, 2))
print(a)
print('-----')
print(b)
print('------')
print(np.hstack((a, b)))        # 水平拼接
print('------')
print(np.vstack((a, b)))        # 垂直拼接

[[-1.  1.]
 [ 0. -1.]]
-----
[[-1.  1.]
 [-1. -1.]]
------
[[-1.  1. -1.  1.]
 [ 0. -1. -1. -1.]]
------
[[-1.  1.]
 [ 0. -1.]
 [-1.  1.]
 [-1. -1.]]


In [5]:
# 分割操作
a = np.floor(np.random.randn(2, 12))
print(a)
print('-------')
print(np.hsplit(a, 3))
print('--------')
print(np.hsplit(a, (3, 5)))
print('-------')
print(np.vsplit(a.T, 3))

[[ 0.  0. -1.  0. -1.  0.  0.  0.  0.  0.  1. -1.]
 [ 1.  1.  2. -1.  1.  0.  0.  1.  1.  0.  0.  0.]]
-------
[array([[ 0.,  0., -1.,  0.],
       [ 1.,  1.,  2., -1.]]), array([[-1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  1.]]), array([[ 0.,  0.,  1., -1.],
       [ 1.,  0.,  0.,  0.]])]
--------
[array([[ 0.,  0., -1.],
       [ 1.,  1.,  2.]]), array([[ 0., -1.],
       [-1.,  1.]]), array([[ 0.,  0.,  0.,  0.,  0.,  1., -1.],
       [ 0.,  0.,  1.,  1.,  0.,  0.,  0.]])]
-------
[array([[ 0.,  1.],
       [ 0.,  1.],
       [-1.,  2.],
       [ 0., -1.]]), array([[-1.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  1.]]), array([[ 0.,  1.],
       [ 0.,  0.],
       [ 1.,  0.],
       [-1.,  0.]])]


In [6]:
data = np.sin(np.arange(20)).reshape((5, 4))
print(data)
ind = np.argmax(data, axis=0)
print(ind)
data_max = data[ind, range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [7]:
a = np.arange(0, 40, 10)
print(a)
b = np.tile(a, (2, 3))      # 重复
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [8]:
# 排序操作
a = np.array([[4, 3, 5], [6, 8, 7]])
print(a)
print(np.sort(a, axis=1))       # 不在原处修改
print(a)
a.sort(axis=1)      # 原处修改
print(a)

[[4 3 5]
 [6 8 7]]
[[3 4 5]
 [6 7 8]]
[[4 3 5]
 [6 8 7]]
[[3 4 5]
 [6 7 8]]


In [9]:
a = np.array([4, 2, 1, 3])
b = np.argsort(a)
print(b)
print(a[b])

[2 1 3 0]
[1 2 3 4]
