In [1]:
# 复制操作
import numpy as np

a = np.arange(12)
b = a           # 共用同一内存空间，不管修改哪一个，另一个也会跟着改变
print(a is b)
b.shape = (3, 4)
print(a.shape)
print(id(a))
print(id(b))
print('--------')
c = a[:]        # 同c = a.view()
print(a)
a[1, 1] = 666
print(c)
print(a)

True
(3, 4)
1301862097584
1301862097584
--------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   2   3]
 [  4 666   6   7]
 [  8   9  10  11]]
[[  0   1   2   3]
 [  4 666   6   7]
 [  8   9  10  11]]


In [2]:
c = a.view()        # 视图复制,相当于浅复制.等同与c = a[:]
print(a is c)
c.shape = (2, 6)
print(a.shape)
print(id(a))
print(id(c))
print('----')
print(a)
print(c)
print('------')
c[0, 4] = 1234      # 会影响a,a改变也会改变c
print(a)
print(c)

False
(3, 4)
1301862097584
1302117160720
----
[[  0   1   2   3]
 [  4 666   6   7]
 [  8   9  10  11]]
[[  0   1   2   3   4 666]
 [  6   7   8   9  10  11]]
------
[[   0    1    2    3]
 [1234  666    6    7]
 [   8    9   10   11]]
[[   0    1    2    3 1234  666]
 [   6    7    8    9   10   11]]


In [3]:
d = a.copy()        # 深复制
print(a is d)
print(a)
print(d)
print('-------')
d[0, 0] = 1234      # 并不影响a
print(a)
print(d)

False
[[   0    1    2    3]
 [1234  666    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234  666    6    7]
 [   8    9   10   11]]
-------
[[   0    1    2    3]
 [1234  666    6    7]
 [   8    9   10   11]]
[[1234    1    2    3]
 [1234  666    6    7]
 [   8    9   10   11]]
