In [1]:
# numpy.array
import numpy as np

vector = np.array([1, 2, 3, 4.0])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(vector, vector.shape, vector.dtype)
print(matrix, matrix.shape, matrix.dtype)

# 按行列截取
print(vector[: 3])
print(vector[2])

print(matrix[:, 0])
print(matrix[1:3, 0:2])

[1. 2. 3. 4.] (4,) float64
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int32
[1. 2. 3.]
3.0
[1 4 7]
[[4 5]
 [7 8]]


In [2]:
vector = np.array([1, 8, 7, 4])
# 按条件截取
v = (vector == 7)
v1 = (vector == 1) | (vector == 7)
print(v)
print(v1)
print(vector[v])
print(vector[v1])

[False False  True False]
[ True False  True False]
[7]
[1 7]


In [3]:
matrix = np.array([[1, 12, 3],
                   [4, 22, 6],
                   [7, 18, 9]])
m = matrix[:, 1] == 12
print(m)
print(matrix[m, :])

[ True False False]
[[ 1 12  3]]


In [4]:
vector = np.array(['1', '8', '7', '4'])
print(vector.dtype)
vector = vector.astype(np.float64)      # vector = vector.astype('float64')
print(vector.dtype)
print(vector)
v = vector.astype(np.bool_)
print(v)
print(v.dtype)

<U1
float64
[1. 8. 7. 4.]
[ True  True  True  True]
bool


In [5]:
vector = np.array([1, 8, 7, 4])
print(vector.min())
print(vector.max())

1
8


In [6]:
matrix = np.array([[1, 12, 3],
                   [4, 22, 6],
                   [7, 18, 9]])

print(matrix)
matrix.sum(axis=1)      # 按行求和，按列求和axis=0

[[ 1 12  3]
 [ 4 22  6]
 [ 7 18  9]]


In [7]:
print(np.arange(15))
a = np.arange(15).reshape((3, 5))
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
15
4


In [8]:
a = np.zeros((3, 4))
b = np.ones((2, 3, 4), dtype=np.int32)
c = np.eye(4, dtype=np.int64)       # 单位矩阵
d = np.empty((3, 4))        # 创建空矩阵，实际有值
print(a)
print(b)
print(c)
print(d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[8.96224980e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 3.69776220e-062 6.87152680e-091 2.42259161e-052]
 [6.58717425e-043 1.79740021e-052 3.99910963e+252 1.46030983e-319]]


In [9]:
a = np.random.random((2, 3))
print(a)
b = np.linspace(0, 5, 16)       # 5 能取到
b1 = b.reshape((4, 4))
print(b)
print(b1)

[[0.04771146 0.89464438 0.07996002]
 [0.54515884 0.73799944 0.98783379]]
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]
[[0.         0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.         2.33333333]
 [2.66666667 3.         3.33333333 3.66666667]
 [4.         4.33333333 4.66666667 5.        ]]


In [10]:
a = np.array([10, 15, 12, 16])
b = np.arange(4)
c = a - b
c1 = c - 1
print(c)
print(c1)
d = b ** 2
q = a < 15
print(d)
print(q)

In [11]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print(A*B)      # 对应位置相乘
print('------')
print(A.dot(B))     # 矩阵相乘,点乘
print('------')
print(np.dot(A, B))     # 矩阵相乘，点乘

[[ 5 12]
 [21 32]]
------
[[19 22]
 [43 50]]
------
[[19 22]
 [43 50]]


In [12]:
a = 'abcdgh'
b = np.fromstring(a, dtype=np.int8)
print(b)

[ 97  98  99 100 103 104]


C:\Users\lxg\Documents\Python\Practice\venv\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  
